### ISSUE TITLE
Criar esboço inicial do layout da página de playlists.

### ISSUE THREAD

**Issue by CodeSwapTeam** [CodeSwapTeam/CodeSwap#11]
Esboço inicial da página de playlists de cursos.
Versão WEB
![image](https://github.com/CodeSwapTeam/CodeSwap/assets/135326589/732152ad-3ee0-4229-9f09-988a2f11322e)

Versão Mobile
![image](https://github.com/CodeSwapTeam/CodeSwap/assets/135326589/42772398-5d7e-411c-b047-2babe356850c)

**Comment by CodeSwapTeam** [comment]
Este esboço será revisado pela Design Aldrielly e @renatoalencarc

**Comment by aldriellyr** [comment]
Primeiro esboço pronto. Aberto a sugestão de mudanças 

![Image](https://github.com/CodeSwapTeam/CodeSwap/assets/166715272/c7bb6f28-64ee-4705-ba39-ad7c56d36cd5)

**Comment by CodeSwapTeam** [comment]
@aldriellyr  muito bom! vou fechar essa issue porque esta página é do layout do usuário deslogado.
