### ISSUE TITLE
Esboço inicial pagina de modulos

### ISSUE THREAD

**Issue by aldriellyr** [CodeSwapTeam/CodeSwap#27]
Fiz as primeiras correções, pra poder incluir as informações de acordo com o que conversamos. Estou trabalhando nos esboços ainda, porém segue abaixo. Vou fazer o do modulo dois, e mando aqui pra vermos como fica. @Shepardy22 Eu vou fazer dois jeitos, igual falamos mais cedo, só pra ter uma base de como ficaria, e vou implementar a questão dos "cursos recomendados" 

![Image](https://github.com/CodeSwapTeam/CodeSwap/assets/166715272/b1015890-40c6-478c-b9e6-d1f42172180f)

![Image](https://github.com/CodeSwapTeam/CodeSwap/assets/166715272/818eacf0-a6bc-4358-9d97-996c030d8862)

A pagina de cursos estendido ficaria assim (abaixo), claro, que terá a barra de rolagem. 

![Image](https://github.com/CodeSwapTeam/CodeSwap/assets/166715272/cdf8a330-83b7-4162-bbe7-9d0929ea68ed)

**Comment by CodeSwapTeam** [comment]
@aldriellyr o design ficou muito bom, porém é preciso ter botões laterais para a navegação do carrossel, porque serão vários módulos dentro do curso.


e no campo de descrição do módulo será exibido os títulos das aulas.


![Image](https://github.com/CodeSwapTeam/CodeSwap/assets/135326589/1687f663-fe04-43a9-9244-a115678dbb8f)





![Image](https://github.com/CodeSwapTeam/CodeSwap/assets/135326589/db999f1b-e8b0-4861-bcca-4bcb9e4245bf)

**Comment by aldriellyr** [comment]
A ideia é não deixar repetitivo, uma vez que quando o aluno acessa ao modulo, ele já terá acesso aos titulos do modulo. 
vou fazer um segundo esboço, do jeito que sugeriu pra vermos como fica

**Comment by Shepardy101** [comment]
@aldriellyr ficou muito bom! 
assim que eu terminar as parte de otimização de armazenagem vou trabalhar pra  salvar as preferências do usuário e conseguir exibir esses cursos recomentados. marcamos essa ISSUE como finalizada assim que tivermos essa página definida.

**Comment by CodeSwapTeam** [comment]
Iniciado a criação do HTML da página do curso
